name: 'Hexlet basics exercises action'
description: 'Action for building and testing language images for hexlet-basics'

inputs:
  DOCKER_USERNAME:
    required: true
  DOCKER_PASSWORD:
    required: true

runs:
  using: 'composite'
  env:
    IMAGE_NAME: hexletbasics/${{ github.event.repository.name }}

  steps:
    - uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.DOCKER_USERNAME }}
        password: ${{ inputs.DOCKER_PASSWORD }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Одна сборка для всех последующих шагов
    - name: Build image
      uses: docker/build-push-action@v6
      with:
        cache-from: type=gha
        cache-to: type=gha,mode=max
        tags: ${{ env.IMAGE_NAME }}:latest
        outputs: type=docker  # сохраняем в локальный docker daemon

    - name: Check
      run: docker compose --file docker-compose.yml up --abort-on-container-exit
      shell: bash

    # Пушим тот же образ без пересборки
    - name: Push latest
      if: ${{ github.event_name == 'push' }}
      run: docker push ${{ env.IMAGE_NAME }}:latest

    - uses: reviewdog/action-languagetool@v1
      with:
        reporter: github-check
        level: info
