name: 'Hexlet basics exercises action'
description: 'Action for build language images hexlet-basics'

inputs:
  DOCKER_USERNAME:
    required: true
  DOCKER_PASSWORD:
    required: true

runs:
  using: 'composite'

  steps:
    - name: Set image name
      run: |
        echo "IMAGE_NAME=hexletbasics/$(echo "$GITHUB_REPOSITORY" | cut -d/ -f2)" >> $GITHUB_ENV
      shell: bash

    - name: Login to Docker Hub
      if: ${{ github.event_name == 'push' }}
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.DOCKER_USERNAME }}
        password: ${{ inputs.DOCKER_PASSWORD }}

    -
      # Add support for more platforms with QEMU (optional)
      # https://github.com/docker/setup-qemu-action
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build
      uses: docker/build-push-action@v6
      with:
        cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:cached
        platforms: linux/amd64,linux/arm64
        load: true
        tags: ${{ env.IMAGE_NAME }}:cached

    - name: Push cached
      if: ${{ github.event_name == 'push' }}
      uses: docker/build-push-action@v6
      with:
        cache-to: type=inline
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ env.IMAGE_NAME }}:cached

    - uses: actions/checkout@v4

    - name: Check
      run: docker compose --file docker-compose.yml up --abort-on-container-exit
      shell: bash

    - name: Push latest
      if: ${{ github.event_name == 'push' }}
      uses: docker/build-push-action@v6
      with:
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ env.IMAGE_NAME }}:latest

    - uses: reviewdog/action-languagetool@v1
      with:
        # github_token: ${{ secrets.github_token }}
        # Change reviewdog reporter if you need [github-pr-check,github-check,github-pr-review].
        reporter: github-check
        # language:
        #   default: 'ru-RU'
        # Change reporter level if you need.
        level: info

    # - name: Spellcheck
    #   uses:  addnab/docker-run-action@v3
    #   with:
    #     image: hexlet/languagetool-cli:latest
    #     options: -v ${{ github.workspace }}/modules:/content
    #     run: node ./bin/run.js check /content/**/*.md
