name: "Hexlet basics exercises action"
description: "Action for building and testing language images for hexlet-basics"

inputs:
  DOCKER_USERNAME:
    description: "Username used to authenticate to ghcr.io"
    required: true
  DOCKER_PASSWORD:
    description: "Token/password used to authenticate to ghcr.io"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v6

    - name: Set image name
      run: |
        echo "IMAGE_NAME=ghcr.io/${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV
      shell: bash

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ inputs.DOCKER_USERNAME }}
        password: ${{ inputs.DOCKER_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Build amd64 image and load it locally for the check step.
    - name: Build (amd64 only, for testing)
      uses: docker/build-push-action@v6
      with:
        platforms: linux/amd64
        load: true
        cache-from: type=gha,scope=${{ github.repository }}-amd64
        cache-to: type=gha,mode=max,scope=${{ github.repository }}-amd64
        tags: ${{ env.IMAGE_NAME }}:test

    - name: Check
      run: docker compose --file docker-compose.yml up --abort-on-container-exit
      shell: bash

    - name: Build and push amd64 image
      if: ${{ github.event_name == 'push' }}
      uses: docker/build-push-action@v6
      with:
        platforms: linux/amd64
        push: true
        cache-from: type=gha,scope=${{ github.repository }}-amd64
        cache-to: type=gha,mode=max,scope=${{ github.repository }}-amd64
        tags: ${{ env.IMAGE_NAME }}:latest-amd64

    - name: Publish latest manifest
      if: ${{ github.event_name == 'push' }}
      shell: bash
      run: |
        set -euo pipefail

        if docker buildx imagetools inspect "${IMAGE_NAME}:latest-arm64" > /dev/null 2>&1; then
          docker buildx imagetools create \
            -t "${IMAGE_NAME}:latest" \
            "${IMAGE_NAME}:latest-amd64" \
            "${IMAGE_NAME}:latest-arm64"
        else
          echo "No arm64 image found, publishing amd64-only latest"
          docker buildx imagetools create \
            -t "${IMAGE_NAME}:latest" \
            "${IMAGE_NAME}:latest-amd64"
        fi
